

openapi: 3.0.0
info:
  title: API
  version: 1.1.0
  description: Swagger API Documentation

servers: 
  - url: http://localhost:5000

paths:
  /comics:
    get:
      summary: Get all comics
      responses:
        '200':
          description: A list of all saved comics