
# name: Comics API Test Pipline

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x]
#         mongodb-version: ['5.0']

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'

#       - name: Start MongoDB
#         uses: supercharge/mongodb-github-action@1.12.0
#         with:
#           mongodb-version: ${{ matrix.mongodb-version }}

#       - name: Install dependencies
#         run: npm ci

#       - name: Run Jest tests
#         run: npm test
#         env:
#           NODE_ENV: test
#           MONGO_URI: mongodb://localhost:27017/comicsdb